"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { useGame } from "@/lib/store";

const RECIPES = [
  { id: "cadence-crib-mobile", name: "Crib Mobile", image: "/images/IMG_6347.jpeg", sound: "cadenceMobile", cost: [{ itemId: "shell-clam", count: 1 }, { itemId: "shell-scallop", count: 1 }, { itemId: "shell-conch", count: 1 }, { itemId: "glass-purple", count: 1 }, { itemId: "glass-pink", count: 1 }, { itemId: "glass-white", count: 1 }, { itemId: "copper-wire", count: 1 }], description: "A shell and sea-glass mobile that gently turns above Cadence's bed." },
  { id: "cadence-clamshell-nightlight", name: "Clamshell Nightlight", image: "/images/IMG_6348.jpeg", sound: "sparkle", cost: [{ itemId: "firefly-jar", count: 1 }, { itemId: "star-sand", count: 1 }, { itemId: "shell-clam", count: 2 }], description: "A softly glowing clamshell nightlight filled with firefly light and sparkling star sand." },
  { id: "cadence-rose-milk-bubble-bath", name: "Rose Milk Bubble Bath", image: "/images/IMG_6349.jpeg", sound: "oceanWaterSplash", cost: [{ itemId: "bottled-rose-milk", count: 1 }, { itemId: "dried-sea-oats", count: 1 }, { itemId: "sea-lavender", count: 1 }], description: "A gentle rose-milk bubble bath with oats and sea lavender." },
  { id: "cadence-snappy-turtle-teether", name: "Snappy Turtle Teether", image: "/images/IMG_0197.jpeg", sound: "sparkle", cost: [{ itemId: "trash-plastic", count: 1 }, { itemId: "luminous-sea-goo", count: 1 }, { itemId: "sea-water", count: 1 }], description: "A seafoam turtle teether inspired by Snappy, with a softly glowing swirl at the center for Cadence." },
] as const;

const DISCOVERIES = [
  { id: "cadence-marshmallow-plushy", name: "Marshmallow Plushy", image: "/images/IMG_6350.jpeg", sound: "babyBabble", description: "A soft fluffy white cat for Cadence to cuddle with." },
  { id: "cadence-shimmering-seashell-rattle", name: "Shimmering Seashell Rattle", image: "/images/IMG_6351.jpeg", sound: "babyRattle", description: "A shimmering rattle filled with rainbow pearls, sea glitter, and tiny seashells." },
  { id: "cadence-signature-beach-ball", name: "Cadence's Signature Beach Ball", image: "/images/IMG_6345.jpeg", sound: "beachBall", description: "Cadence's seafoam mint, baby pink, and white beach ball." },
] as const;

const BABY_FOODS = [
  { id: "food-cadence-warm-rose-milk", name: "Warm Rose Milk", icon: "🍼", sound: "babyBottle", reaction: "Cadence takes the warm rose milk bottle with both hands, drinks happily, then gives a sleepy little baby babble." },
  { id: "food-cadence-sea-pea-puree", name: "Steamed Sea Pea Purée", icon: "🫛", sound: "babySpoon", reaction: "Cadence tastes the smooth sea pea purée, kicks her tiny tail, and makes a trail of delighted heart-shaped bubbles." },
  { id: "food-cadence-sun-berry-mash", name: "Sun-Berry Fruit Mash", icon: "🫐", sound: "babySpoon", reaction: "Cadence tries the sweet sun-berry mash. Her rosy cheeks brighten and she reaches eagerly for another spoonful." },
  { id: "food-cadence-teething-kelp-cookie", name: "Teething Kelp Cookie", icon: "🍪", sound: "cookieCrunch", reaction: "Cadence nibbles the soft kelp cookie, gives a tiny pleased crunch, and giggles as she holds it in both hands." },
] as const;

const PIANO = ["/audio/Piano1.mp3", "/audio/Piano3.mp3", "/audio/Piano-cheerful.mp3"];
const LULLABIES = ["cadence1", "cadence2", "cadence3"] as const;

export default function CadenceNursery({ onClose }: { onClose: () => void }) {
  const { state, craft, cook, play, collectItem, setMusicOverride } = useGame();
  const [message, setMessage] = useState("Cadence splashes her tiny tail and smiles when you enter.");
  const [discovered, setDiscovered] = useState<string[]>([]);
  const [expandedRecipes, setExpandedRecipes] = useState<string[]>([]);
  const [lullaby, setLullaby] = useState<(typeof LULLABIES)[number]>("cadence1");
  const owned = useMemo(() => new Set(state.crafted), [state.crafted]);
  const keepsakeUnlocked = !!state.questProgress["cadence-ducky"];

  useEffect(() => { setMusicOverride(lullaby); return () => setMusicOverride(null); }, [lullaby, setMusicOverride]);

  const announce = (text: string) => setMessage(text);
  const playLocal = (src: string, level = .7) => { const audio = new Audio(src); audio.volume = Math.max(0, Math.min(1, state.audio.master * level)); void audio.play().catch(() => undefined); };
  const playPiano = () => { playLocal(PIANO[Math.floor(Math.random() * PIANO.length)], .72); play("babyLaugh", .28); announce("You play sparkling notes on the shell piano. Cadence giggles and joins the duet while the nursery lullaby continues underneath."); };
  const discover = (item: typeof DISCOVERIES[number]) => { if (discovered.includes(item.id) || (state.inventory[item.id] ?? 0) > 0) { announce(`${item.name} is already tucked safely into Cadence's driftwood toy chest.`); return; } collectItem(item.id, { silent: true }); setDiscovered(old => [...old, item.id]); play(item.sound, .58); play("toyBoxClose", .25); announce(`Discovered ${item.name}. It has been placed in Cadence's driftwood toy chest.`); };
  const make = (recipe: typeof RECIPES[number]) => { if (owned.has(recipe.id)) { announce(`${recipe.name} is already displayed in Cadence's nursery.`); return; } if (craft(recipe.id, [...recipe.cost])) { setExpandedRecipes(old => old.filter(id => id !== recipe.id)); play(recipe.sound, .5); announce(`${recipe.name} crafted. It now appears in Cadence's nursery. Its recipe has been collapsed.`); } else announce(`You do not have all the materials needed for ${recipe.name}.`); };
  const toggleRecipe = (id: string) => setExpandedRecipes(old => old.includes(id) ? old.filter(item => item !== id) : [...old, id]);
  const feed = (food: typeof BABY_FOODS[number]) => {
    const count = state.inventory[food.id] ?? 0;
    if (count < 1) { announce(`There is no ${food.name} ready. Prepare it in the Kitchen first, then bring it back to Cadence.`); return; }
    if (!cook([{ itemId: food.id, count: 1 }], food.id, 0)) { announce(`Cadence's ${food.name} could not be served right now.`); return; }
    play(food.sound, .58);
    if (food.id !== "food-cadence-teething-kelp-cookie") play("babyBabble", .18); else play("babyLaugh", .2);
    announce(`${food.reaction} One serving of ${food.name} was used.`);
  };

  return <div className="fixed inset-0 z-50 overflow-y-auto bg-[#261b36] text-slate-900" role="dialog" aria-modal="true" aria-labelledby="cadence-title">
    <div className="relative min-h-[260px] w-full overflow-hidden"><Image src="/images/IMG_6342.jpeg" alt="Cadence's cozy sea-glass nursery" fill unoptimized className="object-cover" /><div className="absolute inset-0 bg-gradient-to-b from-black/5 via-transparent to-[#261b36]" /><button type="button" onClick={() => { setMusicOverride(null); onClose(); }} className="absolute right-4 top-4 rounded-full bg-white/95 px-4 py-2 font-bold text-rose-900 shadow">Back to Cottage</button><div className="absolute bottom-4 left-4 right-4 rounded-2xl bg-white/90 p-3 shadow"><h1 id="cadence-title" className="font-serif text-xl font-bold text-rose-900">🌸 Cadence's Nursery</h1><p className="text-sm text-rose-800">Play, discover shoreline toys, feed Cady, and craft cozy treasures for her room.</p></div></div>
    <main className="mx-auto max-w-2xl space-y-4 p-4 pb-24">
      <div aria-live="polite" role="status" className="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-900">{message}</div>
      {keepsakeUnlocked ? <section className="rounded-2xl bg-gradient-to-br from-amber-50 to-pink-50 p-4 shadow ring-2 ring-amber-300" aria-labelledby="cadence-keepsakes"><p className="text-[11px] font-bold uppercase tracking-wide text-amber-800">Quest Reward Unlocked</p><h2 id="cadence-keepsakes" className="font-serif text-lg font-bold text-rose-900">🧰 Cadence's Keepsake Chest</h2><p className="mt-1 text-sm text-slate-700">Ducky is safely home for bedtime. Cadence's special heirlooms are now on display.</p><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => { play("babySpoon", .5); announce("You lift Cadence's engraved silver baby spoon. Its handle is decorated with a delicate wave motif."); }} className="rounded-xl bg-white p-3 text-left ring-1 ring-amber-200"><span className="block text-2xl" aria-hidden="true">🥄</span><strong className="block">Engraved Silver Baby Spoon</strong><span className="text-xs text-slate-600">An antique ship relic polished by Kaiana.</span></button><button type="button" onClick={() => { play("babyRattle", .6); play("babyLaugh", .2); announce("The Golden Pearl Rattle gives a delicate crystalline chime. Cadence beams at the sound."); }} className="rounded-xl bg-white p-3 text-left ring-1 ring-amber-200"><span className="block text-2xl" aria-hidden="true">✨</span><strong className="block">Golden Pearl Rattle</strong><span className="text-xs text-slate-600">A golden keepsake inlaid with tiny pink pearls.</span></button></div></section> : <section className="rounded-2xl bg-white/90 p-4 shadow ring-1 ring-slate-300"><h2 className="font-serif text-lg font-bold text-slate-800">🔒 Keepsake Chest</h2><p className="mt-1 text-sm text-slate-600">Cadence's keepsake chest will open after her lost yellow Ducky is rescued through The Great Rubber Ducky Voyage.</p></section>}
      <section className="rounded-2xl bg-white/95 p-4 shadow" aria-labelledby="cadence-music"><h2 id="cadence-music" className="font-serif text-lg font-bold text-rose-900">Nursery Lullabies</h2><p className="mt-1 text-sm">Choose one of Cadence's three background lullabies.</p><div className="mt-3 grid grid-cols-3 gap-2">{LULLABIES.map((key, i) => <button key={key} type="button" aria-pressed={lullaby === key} onClick={() => { setLullaby(key); announce(`Lullaby ${i + 1} is now playing.`); }} className="rounded-xl bg-violet-100 p-3 font-semibold">Lullaby {i + 1}{lullaby === key ? " • Playing" : ""}</button>)}</div></section>
      <section className="rounded-2xl bg-white/95 p-4 shadow" aria-labelledby="cadence-feeding"><h2 id="cadence-feeding" className="font-serif text-lg font-bold text-rose-900">Cadence's Snack Time</h2><p className="mt-1 text-sm text-slate-700">Prepare baby foods in the Kitchen, then bring them here for Cadence. Each feeding uses one serving.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{BABY_FOODS.map(food => { const count = state.inventory[food.id] ?? 0; return <button key={food.id} type="button" onClick={() => feed(food)} aria-label={`${food.name}. ${count} servings ready.`} className="rounded-xl border border-pink-200 bg-pink-50 p-3 text-left"><span className="text-2xl" aria-hidden="true">{food.icon}</span><strong className="ml-2">{food.name}</strong><span className="mt-1 block text-xs text-slate-700">Servings ready: {count}</span><span className="mt-2 block text-sm font-semibold text-rose-800">{count > 0 ? "Feed Cadence" : "Cook in Kitchen first"}</span></button>; })}</div></section>
      <section className="rounded-2xl bg-white/95 p-4 shadow" aria-labelledby="cadence-play"><h2 id="cadence-play" className="font-serif text-lg font-bold text-rose-900">Play & Care</h2><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => { play("beachBall", .6); play("babyLaugh", .3); announce("You roll the beach ball across the rug. Cadence splashes her tail and rolls it back."); }} className="rounded-xl bg-pink-100 p-3 font-semibold">🏖️ Toss Beach Ball</button><button type="button" onClick={playPiano} className="rounded-xl bg-emerald-100 p-3 font-semibold">🎹 Shell Piano Duet</button><button type="button" onClick={() => { play("rockingCradle", .55); announce("You gently rock Cadence's scallop cradle. She cuddles her toys and grows sleepy."); }} className="rounded-xl bg-violet-100 p-3 font-semibold">🌙 Rock the Cradle</button><button type="button" onClick={() => { play("babyRattle", .55); play("babyLaugh", .22); announce("The shimmering seashell rattle jingles. Cadence reaches for it and laughs."); }} className="rounded-xl bg-amber-100 p-3 font-semibold">✨ Shake the Rattle</button></div></section>
      <section className="rounded-2xl bg-white/95 p-4 shadow" aria-labelledby="cadence-craft"><h2 id="cadence-craft" className="font-serif text-lg font-bold text-rose-900">Nursery Crafting</h2><p className="mt-1 text-sm text-slate-700">Craft each nursery decoration once. After it is made, select the item to show or hide its recipe.</p><div className="mt-3 space-y-3">{RECIPES.map(r => { const isOwned = owned.has(r.id); const expanded = !isOwned || expandedRecipes.includes(r.id); const detailsId = `${r.id}-recipe`; return <article key={r.id} className="rounded-xl border border-rose-200 p-3">{isOwned ? <button type="button" aria-expanded={expanded} aria-controls={detailsId} aria-label={`${r.name}, crafted and displayed. ${expanded ? "Hide recipe" : "Show recipe"}.`} onClick={() => toggleRecipe(r.id)} className="flex w-full items-center gap-3 rounded-lg text-left focus-visible:outline focus-visible:outline-4 focus-visible:outline-rose-600"><Image src={r.image} alt="" width={72} height={72} unoptimized className="h-[72px] w-[72px] rounded-lg object-cover" /><span><strong className="block">{r.name}</strong><span className="text-xs font-semibold text-emerald-800">Crafted & Displayed · {expanded ? "Hide recipe" : "Show recipe"}</span></span></button> : <div className="flex gap-3"><Image src={r.image} alt="" width={72} height={72} unoptimized className="h-[72px] w-[72px] rounded-lg object-cover" /><div><h3 className="font-bold">{r.name}</h3><p className="text-xs text-slate-600">{r.description}</p></div></div>}{expanded && <div id={detailsId}>{isOwned && <p className="mt-2 text-xs text-slate-600">{r.description}</p>}<p className="mt-2 text-xs">Requires: {r.cost.map(c => `${c.count} ${c.itemId.replaceAll("-", " ")}`).join(", ")}</p>{isOwned ? <p className="mt-2 text-sm font-bold text-emerald-800">Crafted & Displayed</p> : <button type="button" onClick={() => make(r)} className="mt-2 w-full rounded-lg bg-rose-700 py-2 font-bold text-white">Craft {r.name}</button>}</div>}</article>; })}</div></section>
      <section className="rounded-2xl bg-white/95 p-4 shadow" aria-labelledby="cadence-discoveries"><h2 id="cadence-discoveries" className="font-serif text-lg font-bold text-rose-900">Driftwood Toy Chest</h2><p className="mt-1 text-sm text-slate-700">Special toys discovered along the shoreline are kept here for Cadence.</p><div className="mt-3 grid gap-3">{DISCOVERIES.map(item => { const found = discovered.includes(item.id) || (state.inventory[item.id] ?? 0) > 0; return <button key={item.id} type="button" onClick={() => discover(item)} className="flex w-full items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-left"><Image src={item.image} alt="" width={64} height={64} unoptimized className="h-16 w-16 rounded-lg object-cover" /><span><strong className="block">{item.name}{found ? " • Found" : ""}</strong><span className="text-xs text-slate-700">{item.description}</span></span></button>})}</div></section>
    </main>
  </div>;
}