export interface AquariumSpecies {
  id: string; name: string; babyName: string; habitat: "coral" | "seagrass" | "rocks" | "open"; daysToMature: number; rarity: "common" | "uncommon" | "rare"; emoji: string; imageSrc: string; careNote: string; adultNote: string;
}
export interface AquariumResident { id: string; speciesId: string; arrivedDate: string; }
export const AQUARIUM_SPECIES: AquariumSpecies[] = [
 {id:"seahorse",name:"Seahorse",babyName:"Juvenile Seahorse",habitat:"seagrass",daysToMature:3,rarity:"common",emoji:"🌿",imageSrc:"/images/juvenile-seahorse.png",careNote:"It curls its tail around the seagrass and watches Waverly closely at feeding time.",adultNote:"Its crown is distinct and its curled tail is strong enough for the seagrass."},
 {id:"pufferfish",name:"Pufferfish",babyName:"Baby Pufferfish",habitat:"coral",daysToMature:3,rarity:"common",emoji:"🐡",imageSrc:"/images/baby-pufferfish.png",careNote:"It practices tiny defensive puffs, then settles quickly when the tank is calm.",adultNote:"It has learned to puff up when startled."},
 {id:"clownfish",name:"Clownfish Pair",babyName:"Baby Clownfish Pair",habitat:"coral",daysToMature:4,rarity:"common",emoji:"🐠",imageSrc:"/images/baby-clownfish-pair.png",careNote:"The pair stays close together and is becoming more confident around the nursery anemone.",adultNote:"The pair is ready for a nursery anemone on the reef."},
 {id:"mandarinfish",name:"Mandarinfish",babyName:"Baby Mandarinfish",habitat:"coral",daysToMature:4,rarity:"uncommon",emoji:"🐟",imageSrc:"/images/baby-mandarinfish.png",careNote:"New flecks of color are appearing along its body as it grows.",adultNote:"Intricate colors now cover its body."},
 {id:"yellow-tang",name:"Yellow Tang",babyName:"Baby Yellow Tang",habitat:"open",daysToMature:3,rarity:"common",emoji:"🐟",imageSrc:"/images/baby-yellow-tang.png",careNote:"It is grazing steadily and exploring more of the open-water side of the tank.",adultNote:"Its brilliant yellow coloring has fully developed."},
 {id:"royal-gramma",name:"Royal Gramma",babyName:"Baby Royal Gramma",habitat:"rocks",daysToMature:4,rarity:"common",emoji:"🐟",imageSrc:"/images/baby-royal-gramma.png",careNote:"It has chosen a favorite rock shelter and peeks out whenever Waverly approaches.",adultNote:"Its purple-to-yellow colors glow beside the rock shelters."},
 {id:"cardinalfish",name:"Banggai Cardinalfish",babyName:"Baby Banggai Cardinalfish",habitat:"rocks",daysToMature:4,rarity:"uncommon",emoji:"🐟",imageSrc:"/images/baby-banggai-cardinalfish.png",careNote:"Its long fins are becoming more defined, and it hovers calmly near the rocks.",adultNote:"Its bold black-and-white pattern and long fins are fully formed."},
 {id:"cowfish",name:"Longhorn Cowfish",babyName:"Baby Longhorn Cowfish",habitat:"open",daysToMature:5,rarity:"uncommon",emoji:"🐟",imageSrc:"/images/baby-longhorn-cowfish.png",careNote:"Its boxy little body is growing, and the first hints of its horns are becoming visible.",adultNote:"The tiny yellow box has grown its unmistakable horns."},
 {id:"chromis",name:"Blue-Green Chromis School",babyName:"Baby Chromis School",habitat:"open",daysToMature:3,rarity:"common",emoji:"🐟",imageSrc:"/images/baby-blue-green-chromis-school.png",careNote:"The young chromis are schooling more tightly and changing direction together.",adultNote:"The young fish now move together in a confident school."},
 {id:"flying-gurnard",name:"Flying Gurnard",babyName:"Baby Flying Gurnard",habitat:"open",daysToMature:5,rarity:"uncommon",emoji:"🐟",imageSrc:"/images/baby-flying-gurnard.png",careNote:"Its fins are widening a little each day, though they are not yet fully dramatic.",adultNote:"Its enormous patterned fins now open like underwater wings."},
 {id:"leafy-seadragon",name:"Leafy Seadragon",babyName:"Baby Leafy Seadragon",habitat:"seagrass",daysToMature:6,rarity:"rare",emoji:"🌿",imageSrc:"/images/baby-leafy-seadragon.png",careNote:"Tiny leafy appendages are becoming more elaborate as it rests among the seagrass.",adultNote:"Its elaborate leafy appendages blend beautifully into the seagrass."},
 {id:"emperor-angelfish",name:"Emperor Angelfish",babyName:"Baby Emperor Angelfish",habitat:"coral",daysToMature:6,rarity:"rare",emoji:"🐠",imageSrc:"/images/baby-emperor-angelfish.png",careNote:"Its juvenile ring pattern is beginning to change as new adult markings emerge.",adultNote:"Its juvenile rings have transformed into striking adult stripes."},
 {id:"moonbeam-minnow",name:"Moonbeam Minnow",babyName:"Baby Moonbeam Minnow",habitat:"open",daysToMature:5,rarity:"rare",emoji:"✨",imageSrc:"/images/baby-moonbeam-minnow.png",careNote:"A faint silvery glow is starting to appear when it swims through darker water.",adultNote:"Its silvery body now gives off a soft moonlit glow."},
 {id:"sea-glass-goby",name:"Sea Glass Goby",babyName:"Baby Sea Glass Goby",habitat:"rocks",daysToMature:5,rarity:"rare",emoji:"💎",imageSrc:"/images/baby-sea-glass-goby.png",careNote:"Its body is becoming clearer and more aqua, almost like a piece of sea glass.",adultNote:"Its body has developed translucent aqua sea-glass coloring."},
 {id:"rosefin-butterflyfish",name:"Rosefin Butterflyfish",babyName:"Baby Rosefin Butterflyfish",habitat:"coral",daysToMature:5,rarity:"rare",emoji:"🌸",imageSrc:"/images/baby-rosefin-butterflyfish.png",careNote:"The pale pink color along its fins is becoming stronger and easier to see.",adultNote:"Its delicate pale-pink fins are fully grown."},
 {id:"starlight-lanternfish",name:"Starlight Lanternfish",babyName:"Baby Starlight Lanternfish",habitat:"rocks",daysToMature:6,rarity:"rare",emoji:"✨",imageSrc:"/images/baby-starlight-lanternfish.png",careNote:"Another tiny bioluminescent dot has appeared, giving it a little more starlight.",adultNote:"Every tiny bioluminescent dot now shines like a star."},
];

export const AQUARIUM_SHELL_MILESTONES = [
  { id: "large-sand-dollar", name: "Large Sand Dollar", releases: 5, description: "A broad, pale sand dollar selected by Waverly to mark your first major nursery milestone." },
  { id: "sun-dial-shell", name: "Sun Dial Shell", releases: 10, description: "A beautifully patterned spiral shell with radiating markings like a tiny coastal sundial." },
  { id: "harp-shell", name: "Harp Shell", releases: 15, description: "An elegant collector shell with fine ribbing and a graceful harp-like pattern." },
  { id: "scotch-bonnet", name: "Scotch Bonnet", releases: 16, description: "A prized spotted shell displayed as a record of completing Waverly’s reef research." },
  { id: "golden-unicorn-horn-shell", name: "Golden Unicorn Horn Shell", releases: 16, description: "A long golden spiral shell shaped like a unicorn horn, reserved for completing the full field guide." },
] as const;
export type AquariumShellMilestoneId = typeof AQUARIUM_SHELL_MILESTONES[number]["id"];

export function aquariumDateKey(d=new Date()){return d.toISOString().slice(0,10)}
export function aquariumAgeDays(arrived:string, now=new Date()){const a=new Date(arrived+"T12:00:00");const b=new Date(aquariumDateKey(now)+"T12:00:00");return Math.max(0,Math.floor((b.getTime()-a.getTime())/86400000))}
export function getAquariumSpecies(id:string){return AQUARIUM_SPECIES.find(s=>s.id===id)}
export function aquariumStage(r:AquariumResident, now=new Date()){const s=getAquariumSpecies(r.speciesId);const age=aquariumAgeDays(r.arrivedDate,now);if(!s)return {age,label:"Unknown",mature:false,progress:0};return {age,label:age>=s.daysToMature?"Ready for release":age===0?"New arrival":age<Math.ceil(s.daysToMature/2)?"Growing baby":"Juvenile",mature:age>=s.daysToMature,progress:Math.min(100,Math.round(age/s.daysToMature*100))}}
export function rollBabyFish(excluded:string[]=[], habitat?: AquariumSpecies["habitat"]){const available=AQUARIUM_SPECIES.filter(s=>!excluded.includes(s.id) && (!habitat || s.habitat===habitat));if(!available.length)return null;const weighted=available.flatMap(s=>Array(s.rarity==="common"?6:s.rarity==="uncommon"?3:1).fill(s));return weighted[Math.floor(Math.random()*weighted.length)]}
