export type ItemCategory = "shell" | "glass" | "pearl" | "raw" | "trash" | "special" | "food" | "decor";

export interface ItemDef {
  id: string;
  name: string;
  category: ItemCategory;
  icon: string;
  isEmoji?: boolean;
  rarity: "common" | "uncommon" | "rare";
  sfx: string;
  glows?: boolean;
  artDescription?: string;
}

const ICON_BASE = "https://galaxy-prod.tlcdn.com/gen/user_32o6JOgK3frOagwPkyqjrJpmKC3";

export const ITEMS: Record<string, ItemDef> = {
  "halloween-candy": { id: "halloween-candy", name: "Halloween Candy", category: "food", icon: "🍬", isEmoji: true, rarity: "common", sfx: "craftSuccess" },
  "chocolate-seashells": { id: "chocolate-seashells", name: "Chocolate Seashells", category: "food", icon: "🍫", isEmoji: true, rarity: "common", sfx: "craftSuccess" },
  "orange-sea-glitter": { id: "orange-sea-glitter", name: "Orange Sea Glitter", category: "decor", icon: "✨", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "orange-glaze": { id: "orange-glaze", name: "Orange Glaze", category: "food", icon: "🫙", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "glowing-wax": { id: "glowing-wax", name: "Glowing Wax", category: "raw", icon: "🕯️", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess", glows: true },
  "pumpkin-spice": { id: "pumpkin-spice", name: "Pumpkin Spice", category: "raw", icon: "🎃", isEmoji: true, rarity: "uncommon", sfx: "bagRustle" },
  "ghost-pearl": { id: "ghost-pearl", name: "Ghost Pearl", category: "pearl", icon: "👻", isEmoji: true, rarity: "rare", sfx: "pearl", glows: true },
  "moon-charm": { id: "moon-charm", name: "Moon Charm", category: "special", icon: "🌙", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "carnelian-crystal-pumpkin": { id: "carnelian-crystal-pumpkin", name: "Orange Crystal Pumpkin", category: "decor", icon: "🎃", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "clear-quartz-skull": { id: "clear-quartz-skull", name: "Clear Quartz Skull", category: "decor", icon: "💀", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "black-obsidian-cat": { id: "black-obsidian-cat", name: "Black Obsidian Cat", category: "decor", icon: "🐈‍⬛", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "porcelain-ghost-figurine": { id: "porcelain-ghost-figurine", name: "Porcelain Ghost Figurine", category: "decor", icon: "👻", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "magic-8-ball": { id: "magic-8-ball", name: "Magic 8 Ball", category: "decor", icon: "🎱", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "white-pumpkin": { id: "white-pumpkin", name: "White Pumpkin", category: "decor", icon: "⚪", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "yellow-pumpkin": { id: "yellow-pumpkin", name: "Yellow Pumpkin", category: "decor", icon: "🟡", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "green-pumpkin": { id: "green-pumpkin", name: "Green Pumpkin", category: "decor", icon: "🟢", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "blue-pumpkin": { id: "blue-pumpkin", name: "Blue Pumpkin", category: "decor", icon: "🔵", isEmoji: true, rarity: "rare", sfx: "pearl" },

  "uv-dive-torch": { id: "uv-dive-torch", name: "High-Intensity UV Dive Torch", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "deep-fins": { id: "deep-fins", name: "Weighted Belt & Deep Fins", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "reserve-tank": { id: "reserve-tank", name: "Twin Reserve Tank & Regulator", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "cave-calcite": { id: "cave-calcite", name: "Cave Calcite", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "rough-enhydro": { id: "rough-enhydro", name: "Rough Enhydro Crystal", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "included-quartz": { id: "included-quartz", name: "Sand-Included Quartz", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "glowing-fluorite": { id: "glowing-fluorite", name: "Glowing Fluorite", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "tidal-heart": { id: "tidal-heart", name: "Tidal Heart Enhydro", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "polished-enhydro": { id: "polished-enhydro", name: "Window-Clear Enhydro", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "crystal-walrus": { id: "crystal-walrus", name: "Glowing Crystal Walrus", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "crystal-dolphin": { id: "crystal-dolphin", name: "Glowing Crystal Dolphin", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },
  "mystery-liquid": { id: "mystery-liquid", name: "Mystery Liquid Sample", category: "special", icon: "💎", isEmoji: true, rarity: "rare", sfx: "offshorechip" },

  "shell-nautilus": { id: "shell-nautilus", name: "Nautilus Shell", category: "shell", icon: `${ICON_BASE}/604cb7e3-03ed-411d-97fa-2435e8340fc7.png`, rarity: "uncommon", sfx: "shell" },
  "shell-scallop": { id: "shell-scallop", name: "Scallop Shell", category: "shell", icon: `${ICON_BASE}/e93500d7-8dea-48fa-ad4b-f8bd6439708f.png`, rarity: "common", sfx: "shell" },
  "shell-conch": { id: "shell-conch", name: "Conch Shell", category: "shell", icon: `${ICON_BASE}/43715411-ab07-442e-ae82-563d96c4cc45.png`, rarity: "uncommon", sfx: "shell" },
  "shell-murex": { id: "shell-murex", name: "Murex Shell", category: "shell", icon: `${ICON_BASE}/2cab5259-19a6-4b08-a175-a8a7a2646ceb.png`, rarity: "uncommon", sfx: "shell" },
  "shell-sanddollar": { id: "shell-sanddollar", name: "Sand Dollar", category: "shell", icon: `${ICON_BASE}/12326b57-598d-4ff9-8ec7-407c080ebcf2.png`, rarity: "uncommon", sfx: "sandDollarCoin" },
  "shell-abalone": { id: "shell-abalone", name: "Abalone Shell", category: "shell", icon: `${ICON_BASE}/76cd3095-2306-4a8f-829e-1fbf9bb0a9c3.png`, rarity: "rare", sfx: "shell" },
  "shell-whelk": { id: "shell-whelk", name: "Whelk Shell", category: "shell", icon: `${ICON_BASE}/da1c27b7-a6e7-47de-aea3-ade498f4d32f.png`, rarity: "common", sfx: "shell" },
  "shell-cowrie": { id: "shell-cowrie", name: "Cowrie Shell", category: "shell", icon: `${ICON_BASE}/f876bd27-5332-4e32-b174-4ab56b519762.png`, rarity: "common", sfx: "shell" },
  "shell-clam": { id: "shell-clam", name: "Clam Shell", category: "shell", icon: `${ICON_BASE}/a8a74f62-b113-4ea5-a259-e9d8654703fd.png`, rarity: "common", sfx: "shell" },
  "glass-green": { id: "glass-green", name: "Green Sea Glass", category: "glass", icon: `${ICON_BASE}/b469048c-74c8-4265-b076-1f081c1ba385.png`, rarity: "common", sfx: "seaGlass" },
  "glass-white": { id: "glass-white", name: "White Sea Glass", category: "glass", icon: `${ICON_BASE}/6479472d-3bfb-4905-a536-d94b17b5e631.png`, rarity: "common", sfx: "seaGlass" },
  "glass-amber": { id: "glass-amber", name: "Amber Sea Glass", category: "glass", icon: `${ICON_BASE}/047ee23e-a777-4f76-a312-e408300cc882.png`, rarity: "uncommon", sfx: "seaGlass" },
  "glass-teal": { id: "glass-teal", name: "Teal Sea Glass", category: "glass", icon: `${ICON_BASE}/365c437b-d5b7-44c3-b331-7558435b3399.png`, rarity: "common", sfx: "seaGlass" },
  "glass-blue": { id: "glass-blue", name: "Blue Sea Glass", category: "glass", icon: `${ICON_BASE}/e7d71bb8-f182-4445-8b58-85c07a4bca7e.png`, rarity: "uncommon", sfx: "seaGlass" },
  "glass-pink": { id: "glass-pink", name: "Pink Sea Glass", category: "glass", icon: `${ICON_BASE}/fb533d3a-55e8-4605-b065-13cb622e0a81.png`, rarity: "uncommon", sfx: "seaGlass" },
  "glass-purple": { id: "glass-purple", name: "Purple Sea Glass", category: "glass", icon: `${ICON_BASE}/9ab8c913-a4cc-4cfc-add6-902eb0f92334.png`, rarity: "rare", sfx: "seaGlass" },
  "glass-red": { id: "glass-red", name: "Red Sea Glass", category: "glass", icon: `${ICON_BASE}/92b75a7e-aa9d-4f9f-81b7-fb10a4757fae.png`, rarity: "rare", sfx: "seaGlass" },
  "glass-rainbow": { id: "glass-rainbow", name: "Neon Sea Glass", category: "glass", icon: `${ICON_BASE}/605fd387-dc66-4d00-a7ff-4c5dc2a2a61a.png`, rarity: "rare", sfx: "seaGlass" },
  "pearl-silver": { id: "pearl-silver", name: "Silver Pearl", category: "pearl", icon: `${ICON_BASE}/15fd4c4e-8171-41fc-af4a-ffbccf85b4c3.png`, rarity: "rare", sfx: "pearl" },
  "pearl-pink": { id: "pearl-pink", name: "Pink Pearl", category: "pearl", icon: `${ICON_BASE}/f57a5872-f3e3-4d96-98b8-9f94c880333b.png`, rarity: "rare", sfx: "pearl" },
  "pearl-black": { id: "pearl-black", name: "Black Pearl", category: "pearl", icon: `${ICON_BASE}/1a48a630-bf7c-4308-98e3-ffe384577709.png`, rarity: "rare", sfx: "pearl" },
  "pearl-green": { id: "pearl-green", name: "Green Pearl", category: "pearl", icon: `${ICON_BASE}/7d9cd5d1-d5e6-40eb-b483-e3c49d6db93d.png`, rarity: "rare", sfx: "pearl" },
  "pearl-amber": { id: "pearl-amber", name: "Amber Pearl", category: "pearl", icon: `${ICON_BASE}/da3aff0c-ec75-41e1-a20f-c4f495ef888f.png`, rarity: "rare", sfx: "pearl" },
  "pearl-blue": { id: "pearl-blue", name: "Blue Pearl", category: "pearl", icon: `${ICON_BASE}/d799fd60-32fa-4c8c-a8ec-a2f60ab6c392.png`, rarity: "rare", sfx: "pearl" },
  "pearl-yellow": { id: "pearl-yellow", name: "Yellow Pearl", category: "pearl", icon: "/images/pearls/yellow-pearl.svg", rarity: "rare", sfx: "pearl" },
  "pearl-purple": { id: "pearl-purple", name: "Purple Pearl", category: "pearl", icon: "/images/pearls/purple-pearl.svg", rarity: "rare", sfx: "pearl" },
  "pearl-orange": { id: "pearl-orange", name: "Orange Pearl", category: "pearl", icon: "/images/pearls/orange-pearl.svg", rarity: "rare", sfx: "pearl" },
  "pearl-red": { id: "pearl-red", name: "Red Pearl", category: "pearl", icon: "/images/pearls/red-pearl.svg", rarity: "rare", sfx: "pearl" },
  "pearl-white": { id: "pearl-white", name: "White Pearl", category: "pearl", icon: "/images/pearls/white-pearl.svg", rarity: "rare", sfx: "pearl" },
  "raw-driftwood-arch": { id: "raw-driftwood-arch", name: "Driftwood", category: "raw", icon: `${ICON_BASE}/0f39c941-3590-4858-9c41-36498d6a0a6c.png`, rarity: "common", sfx: "wood" },
  "raw-driftwood-planks": { id: "raw-driftwood-planks", name: "Weathered Plank", category: "raw", icon: `${ICON_BASE}/eb0500d4-6d90-40d7-9de5-97e94423a255.png`, rarity: "uncommon", sfx: "wood" },
  "raw-barnacle-wood": { id: "raw-barnacle-wood", name: "Barnacled Wood", category: "raw", icon: `${ICON_BASE}/2831f0ac-862c-4fb8-8036-0a7a74df36f6.png`, rarity: "uncommon", sfx: "wood" },
  "raw-stone": { id: "raw-stone", name: "Smooth Stone", category: "raw", icon: `${ICON_BASE}/a05a5d04-c254-4f79-9ed8-cbda421fdcd0.png`, rarity: "common", sfx: "stone" },
  "raw-pebbles": { id: "raw-pebbles", name: "Pebbles", category: "raw", icon: `${ICON_BASE}/33471acf-63cc-4452-958a-fc867d37b401.png`, rarity: "common", sfx: "stone" },
  "coconut": { id: "coconut", name: "Coconut", category: "raw", icon: "🥥", isEmoji: true, rarity: "common", sfx: "coconut" },
  "dry-palm-frond": { id: "dry-palm-frond", name: "Dry Palm Frond", category: "raw", icon: "🌴", isEmoji: true, rarity: "common", sfx: "groveLeafRustle" },
  "sweet-green-coconut": { id: "sweet-green-coconut", name: "Sweet Green Coconut", category: "raw", icon: "🥥", isEmoji: true, rarity: "rare", sfx: "groveCoconutImpact" },
  "coastal-brambleberry": { id: "coastal-brambleberry", name: "Coastal Brambleberry", category: "raw", icon: "🫐", isEmoji: true, rarity: "common", sfx: "groveBerryPick" },
  "wild-dewdrop-currant": { id: "wild-dewdrop-currant", name: "Wild Dewdrop Currant", category: "raw", icon: "🫐", isEmoji: true, rarity: "rare", sfx: "groveBerryPick" },
  "wild-lemongrass": { id: "wild-lemongrass", name: "Wild Lemongrass", category: "raw", icon: "🌾", isEmoji: true, rarity: "common", sfx: "groveHerbSnip" },
  "coastal-beach-mint": { id: "coastal-beach-mint", name: "Coastal Beach Mint", category: "raw", icon: "🌿", isEmoji: true, rarity: "common", sfx: "groveHerbSnip" },
  "rain-lily-blossom": { id: "rain-lily-blossom", name: "Rain-Lily Blossom", category: "raw", icon: "🌼", isEmoji: true, rarity: "rare", sfx: "groveHerbSnip" },
  "dune-ginger": { id: "dune-ginger", name: "Dune Ginger", category: "raw", icon: "🫚", isEmoji: true, rarity: "common", sfx: "groveRootPull" },
  "sweet-island-cane": { id: "sweet-island-cane", name: "Sweet Island Cane", category: "raw", icon: "🎋", isEmoji: true, rarity: "uncommon", sfx: "groveRootPull" },
  "storm-fiddlehead": { id: "storm-fiddlehead", name: "Storm Fiddlehead", category: "raw", icon: "🌱", isEmoji: true, rarity: "rare", sfx: "groveRootPull" },
  "golden-island-pumpkin": { id: "golden-island-pumpkin", name: "Golden Island Pumpkin", category: "raw", icon: "🎃", isEmoji: true, rarity: "uncommon", sfx: "groveItemPickup" },
  "miniature-sugar-squash": { id: "miniature-sugar-squash", name: "Miniature Sugar Squash", category: "raw", icon: "🎃", isEmoji: true, rarity: "uncommon", sfx: "groveItemPickup" },
  "winter-spice-bark": { id: "winter-spice-bark", name: "Winter Spice Bark", category: "raw", icon: "🪵", isEmoji: true, rarity: "uncommon", sfx: "groveLeafRustle" },
  "dried-sugar-berries": { id: "dried-sugar-berries", name: "Dried Sugar Berries", category: "raw", icon: "🍇", isEmoji: true, rarity: "uncommon", sfx: "groveBerryPick" },
  "sea-peas": { id: "sea-peas", name: "Sea Peas", category: "raw", icon: "🫛", isEmoji: true, rarity: "common", sfx: "groveHerbSnip" },
  "sea-parsley": { id: "sea-parsley", name: "Sea Parsley", category: "raw", icon: "🌿", isEmoji: true, rarity: "common", sfx: "groveHerbSnip" },
  "rosemary": { id: "rosemary", name: "Rosemary", category: "raw", icon: "🌿", isEmoji: true, rarity: "common", sfx: "groveHerbSnip" },
  "sea-lavender": { id: "sea-lavender", name: "Sea Lavender", category: "raw", icon: "🪻", isEmoji: true, rarity: "uncommon", sfx: "groveHerbSnip" },
  "strawberry": { id: "strawberry", name: "Strawberry", category: "raw", icon: "🍓", isEmoji: true, rarity: "common", sfx: "groveBerryPick" },
  "blueberry": { id: "blueberry", name: "Blueberry", category: "raw", icon: "🫐", isEmoji: true, rarity: "common", sfx: "groveBerryPick" },
  "raspberry": { id: "raspberry", name: "Raspberry", category: "raw", icon: "🍓", isEmoji: true, rarity: "common", sfx: "groveBerryPick" },
  "pineapple": { id: "pineapple", name: "Pineapple", category: "raw", icon: "🍍", isEmoji: true, rarity: "uncommon", sfx: "groveItemPickup" },
  "banana": { id: "banana", name: "Banana", category: "raw", icon: "🍌", isEmoji: true, rarity: "common", sfx: "groveItemPickup" },
  "grapes": { id: "grapes", name: "Grapes", category: "raw", icon: "🍇", isEmoji: true, rarity: "common", sfx: "groveBerryPick" },
  "lemon": { id: "lemon", name: "Lemon", category: "raw", icon: "🍋", isEmoji: true, rarity: "uncommon", sfx: "groveItemPickup" },
  "tea-bags": { id: "tea-bags", name: "Tea Bags", category: "raw", icon: "🫖", isEmoji: true, rarity: "common", sfx: "bagRustle" },
  "vanilla": { id: "vanilla", name: "Vanilla", category: "raw", icon: "🌼", isEmoji: true, rarity: "common", sfx: "bagRustle" },
  "cocoa-powder": { id: "cocoa-powder", name: "Cocoa Powder", category: "raw", icon: "🍫", isEmoji: true, rarity: "common", sfx: "bagRustle" },
  "flour": { id: "flour", name: "Flour", category: "raw", icon: "🌾", isEmoji: true, rarity: "common", sfx: "bagRustle" },
  "eggs": { id: "eggs", name: "Eggs", category: "raw", icon: "🥚", isEmoji: true, rarity: "common", sfx: "bagRustle" },
  "trash-plastic": { id: "trash-plastic", name: "Plastic Debris", category: "trash", icon: "🗑️", isEmoji: true, rarity: "common", sfx: "plastic" },
  "trophy-map": { id: "trophy-map", name: "Old Nautical Map", category: "special", icon: "🗺️", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "trophy-compass": { id: "trophy-compass", name: "Brass Compass", category: "special", icon: "🧭", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "trophy-diving-gear": { id: "trophy-diving-gear", name: "Diving Gear", category: "special", icon: "🤿", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "antique-copper-kettle": { id: "antique-copper-kettle", name: "Maeve's Antique Copper Kettle", category: "special", icon: "🫖", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "trophy-nautilus": { id: "trophy-nautilus", name: "Golden Nautilus Shell", category: "special", icon: "🐚", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "trophy-brass-dial": { id: "trophy-brass-dial", name: "Weathered Brass Dial", category: "special", icon: "🕰️", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "trophy-ship-bell": { id: "trophy-ship-bell", name: "Old Ship Bell", category: "special", icon: "🔔", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "trophy-rose-window": { id: "trophy-rose-window", name: "Mosaic Rose Window Blueprints", category: "special", icon: "🪟", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "wild-beach-plum": { id: "wild-beach-plum", name: "Wild Beach Plum", category: "raw", icon: "🫠", isEmoji: true, rarity: "uncommon", sfx: "driftwood" },
  "sea-rose-petal": { id: "sea-rose-petal", name: "Sea Rose Petal", category: "raw", icon: "🌸", isEmoji: true, rarity: "uncommon", sfx: "shell" },
  "seaweed-fronds": { id: "seaweed-fronds", name: "Seaweed Fronds", category: "raw", icon: "🌿", isEmoji: true, rarity: "common", sfx: "seaweedCollect" },
  "soothing-sea-salt": { id: "soothing-sea-salt", name: "Soothing Sea Salt", category: "raw", icon: "🧂", isEmoji: true, rarity: "common", sfx: "salt" },
  "beach-ball": { id: "beach-ball", name: "Beach Ball", category: "raw", icon: "🏐", isEmoji: true, rarity: "uncommon", sfx: "beachBall" },
  "copper-wire": { id: "copper-wire", name: "Weathered Copper Wire", category: "raw", icon: "〰️", isEmoji: true, rarity: "uncommon", sfx: "driftwood" },
  "hemp-thread": { id: "hemp-thread", name: "Hemp Thread", category: "raw", icon: "🧵", isEmoji: true, rarity: "common", sfx: "driftwood" },
  "coconut-cream": { id: "coconut-cream", name: "Coconut Cream", category: "special", icon: "🥥", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "luminous-sea-goo": { id: "luminous-sea-goo", name: "Luminous Sea-Goo", category: "special", icon: "✨", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "recycled-rubber": { id: "recycled-rubber", name: "Recycled Rubber Strip", category: "special", icon: "♻️", isEmoji: true, rarity: "uncommon", sfx: "plastic" },
  "pearl-deepsea": { id: "pearl-deepsea", name: "Deep Sea Pearl", category: "special", icon: "🔵", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "shell-flake-blue": { id: "shell-flake-blue", name: "Iridescent Blue Shell Flake", category: "special", icon: "🔷", isEmoji: true, rarity: "rare", sfx: "shell" },
  "nautilus-flake": { id: "nautilus-flake", name: "Iridescent Nautilus Flake", category: "special", icon: "🌀", isEmoji: true, rarity: "rare", sfx: "shell" },
  "star-sand": { id: "star-sand", name: "Sparkling Star-Sand", category: "special", icon: "🌠", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "food-beach-plum-jelly": { id: "food-beach-plum-jelly", name: "Beach Plum Jelly", category: "food", icon: "🫙", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "food-sea-rose-milk": { id: "food-sea-rose-milk", name: "Soothing Sea-Rose Milk", category: "food", icon: "🥛", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "bottled-rose-milk": { id: "bottled-rose-milk", name: "Old-Fashioned Bottled Rose Milk", category: "food", icon: "/images/rose-milk-bottle.jpeg", rarity: "rare", sfx: "roseMilkBottle" },
  "food-seaweed-chips": { id: "food-seaweed-chips", name: "Crispy Seaweed Chips", category: "food", icon: "🍟", isEmoji: true, rarity: "common", sfx: "craftSuccess" },
  "food-campfire-marshmallow": { id: "food-campfire-marshmallow", name: "Campfire Marshmallow", category: "food", icon: "🍡", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "sea-lettuce": { id: "sea-lettuce", name: "Fresh Sea Lettuce", category: "raw", icon: "🥬", isEmoji: true, rarity: "uncommon", sfx: "seaweedCollect" },
  "food-sea-lettuce-wrap": { id: "food-sea-lettuce-wrap", name: "Sea Lettuce Garden Wrap", category: "food", icon: "🌯", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "food-golden-pumpkin-bisque": { id: "food-golden-pumpkin-bisque", name: "Golden Pumpkin Bisque", category: "food", icon: "🥣", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "food-sea-rose-pumpkin-tart": { id: "food-sea-rose-pumpkin-tart", name: "Sea Rose Pumpkin Tart", category: "food", icon: "🥧", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "food-island-spiced-gingerbread": { id: "food-island-spiced-gingerbread", name: "Island Spiced Gingerbread", category: "food", icon: "🍪", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "food-coastal-spiced-cocoa": { id: "food-coastal-spiced-cocoa", name: "Frothy Coastal Spiced Cocoa", category: "food", icon: "☕", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "food-sweet-sugar-berry-tea": { id: "food-sweet-sugar-berry-tea", name: "Sweet Sugar Berry Tea", category: "food", icon: "🫖", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "food-lemon-tea": { id: "food-lemon-tea", name: "Lemon Tea", category: "food", icon: "🍵", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "food-mint-tea": { id: "food-mint-tea", name: "Mint Tea", category: "food", icon: "🍵", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "tide-pool-keepsake": { id: "tide-pool-keepsake", name: "Tide-Pool Field Notes", category: "special", icon: "📘", isEmoji: true, rarity: "rare", sfx: "questComplete" },

  "washed-up-canvas": { id: "washed-up-canvas", name: "Washed-Up Canvas", category: "raw", icon: "⛵", isEmoji: true, rarity: "uncommon", sfx: "driftwood" },
  "dried-sea-oats": { id: "dried-sea-oats", name: "Dried Sea Oats", category: "raw", icon: "🌾", isEmoji: true, rarity: "common", sfx: "driftwood" },
  "shiny-soda-tab": { id: "shiny-soda-tab", name: "Shiny Soda Tab", category: "trash", icon: "🥫", isEmoji: true, rarity: "common", sfx: "sodaTab" },
  "driftwood-oar": { id: "driftwood-oar", name: "Weathered Driftwood Oar", category: "raw", icon: "🛶", isEmoji: true, rarity: "uncommon", sfx: "wood" },
  "sealed-frosted-bottle": { id: "sealed-frosted-bottle", name: "Sealed Frosted Bottle", category: "special", icon: "🍾", isEmoji: true, rarity: "uncommon", sfx: "bottleGlass" },
  "empty-glass-bottle": { id: "empty-glass-bottle", name: "Empty Frosted Glass Bottle", category: "raw", icon: "🍾", isEmoji: true, rarity: "common", sfx: "bottleGlass" },
  "bookmark-cozy-marshmallow": { id: "bookmark-cozy-marshmallow", name: "Cozy Coastal Bookmark: Toasted Marshmallow", category: "special", icon: "/images/bookmarks/cozy-marshmallow-bookmark.jpeg", rarity: "rare", sfx: "notebookPage", artDescription: "An illustrated tassel bookmark showing Marshmallow, the white lighthouse cat, beside the lighthouse with a perfectly toasted marshmallow, tea, a star chart, coastal stones, sea glass, and constellations." },
  "bookmark-cozy-maeve-kettle": { id: "bookmark-cozy-maeve-kettle", name: "Cozy Coastal Bookmark: Maeve's Kettle", category: "special", icon: "/images/bookmarks/maeve-kettle-bookmark.jpeg", rarity: "rare", sfx: "notebookPage", artDescription: "An illustrated tassel bookmark showing Marshmallow, the white lighthouse cat, beside Maeve's weathered copper kettle, two cups of tea, a star chart, coastal stones, sea glass, and constellations." },
  "honeybell-seed": { id: "honeybell-seed", name: "Golden Honeybell Seed", category: "special", icon: "🌱", isEmoji: true, rarity: "rare", sfx: "groveItemPickup" },
  "beeswax-jar": { id: "beeswax-jar", name: "Jar of Coastal Beeswax", category: "special", icon: "🫙", isEmoji: true, rarity: "rare", sfx: "honeyJar" },
  "coastal-honey-jar": { id: "coastal-honey-jar", name: "Jar of Coastal Honey", category: "food", icon: "🍯", isEmoji: true, rarity: "rare", sfx: "honeyJar" },
  "coastal-beeswax-candle": { id: "coastal-beeswax-candle", name: "Sea-Rose Coastal Candle", category: "decor", icon: "/images/coastal-beeswax-candle.jpeg", rarity: "rare", sfx: "candleLight", artDescription: "A creamy white beeswax candle decorated with pastel coastal flowers, sea-rose petals, scallop and spiral shells, a small starfish, and a natural twine bow." },
  "tidal-pearl-choker": { id: "tidal-pearl-choker", name: "Tidal Pearl Choker", category: "decor", icon: "📿", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "sand-pink": { id: "sand-pink", name: "Pastel Pink Sand", category: "raw", icon: "🌸", isEmoji: true, rarity: "uncommon", sfx: "shell" },
  "sand-teal": { id: "sand-teal", name: "Deep Ocean Teal Sand", category: "raw", icon: "🌊", isEmoji: true, rarity: "uncommon", sfx: "seaGlass" },
  "sand-apricot": { id: "sand-apricot", name: "Warm Apricot Sand", category: "raw", icon: "🏜️", isEmoji: true, rarity: "uncommon", sfx: "driftwood" },
  "sand-snow-white": { id: "sand-snow-white", name: "Snow-White Sand", category: "raw", icon: "⚪", isEmoji: true, rarity: "uncommon", sfx: "shell" },
  "sand-black-obsidian": { id: "sand-black-obsidian", name: "Black Obsidian Sand", category: "raw", icon: "⚫", isEmoji: true, rarity: "uncommon", sfx: "stone", artDescription: "Deep black sand with a subtle glossy sparkle." },
  "sand-red-ruby": { id: "sand-red-ruby", name: "Red Ruby Sand", category: "raw", icon: "🔴", isEmoji: true, rarity: "uncommon", sfx: "stone", artDescription: "Rich, dark ruby-red sand." },
  "sand-green-leaf": { id: "sand-green-leaf", name: "Green Leaf Sand", category: "raw", icon: "🍃", isEmoji: true, rarity: "uncommon", sfx: "groveLeafRustle", artDescription: "Leafy green sand with tiny leaves mixed throughout." },
  "sand-pumpkin-orange": { id: "sand-pumpkin-orange", name: "Pumpkin Orange Sand", category: "raw", icon: "🎃", isEmoji: true, rarity: "rare", sfx: "driftwood" },
  "sand-candy-corn-swirl": { id: "sand-candy-corn-swirl", name: "Candy Corn Swirl Sand", category: "raw", icon: "🍬", isEmoji: true, rarity: "rare", sfx: "shell" },
  "boo-sand-art-tool-set": { id: "boo-sand-art-tool-set", name: "Boo's Sand Art Tool Set", category: "special", icon: "/images/boo-sand-art-tools.jpeg", rarity: "uncommon", sfx: "craftSuccess", artDescription: "Boo's handmade sand art tools: an orange striped scoop, two pale green bone-handled shovels and sieves, and a small funnel, arranged against driftwood on the sand." },
  "salt-crystal-pink": { id: "salt-crystal-pink", name: "Raw Pink Salt Crystal", category: "raw", icon: "🧂", isEmoji: true, rarity: "uncommon", sfx: "salt" },
  "firefly-jar": { id: "firefly-jar", name: "Glowing Firefly Jar", category: "special", icon: "🏮", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "sea-water": { id: "sea-water", name: "Jar of Sea Water", category: "raw", icon: "💧", isEmoji: true, rarity: "common", sfx: "liquidBottle" },

  "beach-umbrella": { id: "beach-umbrella", name: "Beach Umbrella", category: "decor", icon: "⛱️", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "picnic-basket": { id: "picnic-basket", name: "Picnic Basket", category: "decor", icon: "🧺", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "beach-bag": { id: "beach-bag", name: "Beach Bag", category: "decor", icon: "👜", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "coastal-salt-lamp": { id: "coastal-salt-lamp", name: "Coastal Salt Lamp", category: "decor", icon: "🔮", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "woven-sun-hat": { id: "woven-sun-hat", name: "Woven Sun Hat", category: "decor", icon: "👒", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "wind-chime": { id: "wind-chime", name: "Melodic Wind Chime", category: "decor", icon: "🎐", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "shoreline-snow-globe": { id: "shoreline-snow-globe", name: "Shoreline Snow Globe", category: "decor", icon: "🔮", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "inflatable-raft": { id: "inflatable-raft", name: "Inflatable Rubber Raft", category: "decor", icon: "🛟", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "seaside-air-pump": { id: "seaside-air-pump", name: "Seaside Air Pump", category: "special", icon: "🪠", isEmoji: true, rarity: "rare", sfx: "airPump" },
  "vintage-beach-blanket": { id: "vintage-beach-blanket", name: "Vintage Beach Blanket", category: "decor", icon: "🧺", isEmoji: true, rarity: "rare", sfx: "bagRustle" },
  "misty-moon-lantern": { id: "misty-moon-lantern", name: "Misty's Moon Jelly Lantern", category: "decor", icon: "🏮", isEmoji: true, rarity: "rare", sfx: "pearl", glows: true },
  "bottle-sunset-shoreline": { id: "bottle-sunset-shoreline", name: "Sunset Shoreline Bottle", category: "decor", icon: "🌇", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "bottle-subaquatic-sandbar": { id: "bottle-subaquatic-sandbar", name: "Sub-Aquatic Sandbar Bottle", category: "decor", icon: "🫧", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "bottle-legendary-tidepool": { id: "bottle-legendary-tidepool", name: "Legendary Tide-Pool Glimmer", category: "decor", icon: "💎", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "beach-bottle": { id: "beach-bottle", name: "Beach in a Bottle", category: "decor", icon: "🏝️", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "mosaic-moonlit-tide": { id: "mosaic-moonlit-tide", name: "Moonlit Tide Mosaic", category: "decor", icon: "🌙", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "mosaic-rainbow-fish": { id: "mosaic-rainbow-fish", name: "Rainbow Fish Mosaic", category: "decor", icon: "🐠", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "mosaic-seaglass-flower": { id: "mosaic-seaglass-flower", name: "Sea Glass Flower Mosaic", category: "decor", icon: "🌸", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "sandcastle-masterpiece": { id: "sandcastle-masterpiece", name: "Sandcastle Masterpiece Keepsake", category: "decor", icon: "🏰", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "picnic-packed-keepsake": { id: "picnic-packed-keepsake", name: "Perfectly Packed Picnic Keepsake", category: "special", icon: "🧺", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "snappy-current-keepsake": { id: "snappy-current-keepsake", name: "Snappy's Current Ride Keepsake", category: "special", icon: "🐢", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "moonstone": { id: "moonstone", name: "Moonstone", category: "special", icon: "🌙", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "star-wish-bottle": { id: "star-wish-bottle", name: "Star Wish Bottle", category: "special", icon: "⭐", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "bioluminescent-shard": { id: "bioluminescent-shard", name: "Bioluminescent Shard", category: "special", icon: "✨", isEmoji: true, rarity: "rare", sfx: "seaGlass" },
  "tarnished-compass": { id: "tarnished-compass", name: "Tarnished Compass", category: "special", icon: "🧭", isEmoji: true, rarity: "uncommon", sfx: "questComplete" },
  "locket": { id: "locket", name: "Antique Locket", category: "special", icon: "📿", isEmoji: true, rarity: "uncommon", sfx: "pearl" },
  "carnelian": { id: "carnelian", name: "Deep-Sea Carnelian", category: "special", icon: "🔺", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "moonstone-moon": { id: "moonstone-moon", name: "Glowing Moonstone Moon", category: "special", icon: "🌙", isEmoji: true, rarity: "rare", sfx: "pearl", glows: true },
  "carnelian-heart": { id: "carnelian-heart", name: "Carnelian Heart", category: "special", icon: "🧡", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "charm-green-leaf": { id: "charm-green-leaf", name: "Green Leaf Charm", category: "special", icon: "🍃", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "pendant-red-apple": { id: "pendant-red-apple", name: "Red Apple Pendant", category: "special", icon: "🍎", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "blueprint-beach-hut": { id: "blueprint-beach-hut", name: "Beach Hut Blueprints", category: "special", icon: "📐", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "blueprint-library": { id: "blueprint-library", name: "Library Blueprints", category: "special", icon: "📚", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "map-underwater-crystal-cave": { id: "map-underwater-crystal-cave", name: "Underwater Crystal Cave Map", category: "special", icon: "🗺️", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "pearl-rainbow": { id: "pearl-rainbow", name: "Rainbow Pearl", category: "pearl", icon: "🌈", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "pearl-gold": { id: "pearl-gold", name: "Gold Pearl", category: "pearl", icon: "🟡", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "pearl-glow-dark": { id: "pearl-glow-dark", name: "Glow-in-the-Dark Pearl", category: "pearl", icon: "⚪", isEmoji: true, rarity: "rare", sfx: "pearl", glows: true },
  "glass-aquamarine-glow": { id: "glass-aquamarine-glow", name: "Glowing Aquamarine Sea Glass", category: "glass", icon: "💎", isEmoji: true, rarity: "rare", sfx: "seaGlass", glows: true },
  "gold-world-globe": { id: "gold-world-globe", name: "Gold World Globe", category: "special", icon: "🌐", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "bag-old-coins": { id: "bag-old-coins", name: "Bag of Old Coins", category: "special", icon: "💰", isEmoji: true, rarity: "rare", sfx: "sandDollarCoin" },
  "old-coin": { id: "old-coin", name: "Old Coin", category: "special", icon: "🪙", isEmoji: true, rarity: "uncommon", sfx: "sandDollarCoin" },
  "moss-agate": { id: "moss-agate", name: "Moss Agate Cluster", category: "special", icon: "🟢", isEmoji: true, rarity: "uncommon", sfx: "pearl" },
  "coral-bulb": { id: "coral-bulb", name: "Coral Bulb", category: "raw", icon: "🪸", isEmoji: true, rarity: "common", sfx: "driftwood" },
  "sea-berry": { id: "sea-berry", name: "Sea Berry", category: "food", icon: "🫐", isEmoji: true, rarity: "common", sfx: "shell" },
  "kelp": { id: "kelp", name: "Kelp", category: "raw", icon: "🌿", isEmoji: true, rarity: "common", sfx: "seaweedCollect" },
  "fertilizer": { id: "fertilizer", name: "Sea Fertilizer", category: "raw", icon: "🌱", isEmoji: true, rarity: "common", sfx: "driftwood" },
  "ribbon": { id: "ribbon", name: "Silk Ribbon", category: "decor", icon: "🎀", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "iridescent-shell": { id: "iridescent-shell", name: "Iridescent Shell", category: "shell", icon: "🐚", isEmoji: true, rarity: "uncommon", sfx: "shell" },
  "mother-of-pearl": { id: "mother-of-pearl", name: "Mother-of-Pearl", category: "pearl", icon: "🦪", isEmoji: true, rarity: "rare", sfx: "pearl" },
  "golden-feather": { id: "golden-feather", name: "Penelope's Golden Feather", category: "special", icon: "🪶", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "pattern-pastel-shell-set": { id: "pattern-pastel-shell-set", name: "Pastel Shell Paint Pattern Set", category: "special", icon: "🎨", isEmoji: true, rarity: "rare", sfx: "paintPigment" },
  "painted-shell": { id: "painted-shell", name: "Hand-Painted Shell", category: "decor", icon: "🐚", isEmoji: true, rarity: "uncommon", sfx: "paintPigment" },
  "deep-sea-seed": { id: "deep-sea-seed", name: "Deep-Sea Seed", category: "raw", icon: "🌰", isEmoji: true, rarity: "uncommon", sfx: "driftwood" },
  "rare-soil": { id: "rare-soil", name: "Rare Enriched Soil", category: "raw", icon: "🟤", isEmoji: true, rarity: "uncommon", sfx: "driftwood" },
  "ship-chart": { id: "ship-chart", name: "Weathered Ship Chart", category: "special", icon: "🗺️", isEmoji: true, rarity: "uncommon", sfx: "questComplete" },
  "spyglass-lens": { id: "spyglass-lens", name: "Spyglass Lens", category: "special", icon: "🔍", isEmoji: true, rarity: "uncommon", sfx: "questComplete" },
  "seed-beach-rose": { id: "seed-beach-rose", name: "Beach Rose Seeds", category: "raw", icon: "🌹", isEmoji: true, rarity: "uncommon", sfx: "groveHerbSnip" },
  "seed-sea-holly": { id: "seed-sea-holly", name: "Sea Holly Seeds", category: "raw", icon: "💠", isEmoji: true, rarity: "uncommon", sfx: "groveHerbSnip" },
  "seed-seaside-daisy": { id: "seed-seaside-daisy", name: "Seaside Daisy Seeds", category: "raw", icon: "🌼", isEmoji: true, rarity: "uncommon", sfx: "groveHerbSnip" },
  "seed-coastal-sunflower": { id: "seed-coastal-sunflower", name: "Coastal Sunflower Seeds", category: "raw", icon: "🌻", isEmoji: true, rarity: "uncommon", sfx: "groveHerbSnip" },
  "seed-dune-evening-primrose": { id: "seed-dune-evening-primrose", name: "Dune Evening Primrose Seeds", category: "raw", icon: "🌙", isEmoji: true, rarity: "rare", sfx: "groveHerbSnip" },
  "seed-saltmarsh-mallow": { id: "seed-saltmarsh-mallow", name: "Saltmarsh Mallow Seeds", category: "raw", icon: "🌸", isEmoji: true, rarity: "rare", sfx: "groveHerbSnip" },
  "seed-sea-morning-glory": { id: "seed-sea-morning-glory", name: "Sea Morning Glory Seeds", category: "raw", icon: "🪻", isEmoji: true, rarity: "rare", sfx: "groveHerbSnip" },
  "furniture-beach-chair": { id: "furniture-beach-chair", name: "Beach Chair", category: "decor", icon: "🏖️", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "furniture-bird-bath": { id: "furniture-bird-bath", name: "Bird Bath", category: "decor", icon: "🐦", isEmoji: true, rarity: "uncommon", sfx: "liquidBottle" },
  "furniture-water-fountain": { id: "furniture-water-fountain", name: "Water Fountain", category: "decor", icon: "⛲", isEmoji: true, rarity: "rare", sfx: "liquidBottle" },
  "furniture-clamshell-cat-bed": { id: "furniture-clamshell-cat-bed", name: "Marshmallow's Clamshell Cat Bed", category: "decor", icon: "🛏️", isEmoji: true, rarity: "rare", sfx: "craftSuccess" },
  "binoculars": { id: "binoculars", name: "Binoculars", category: "special", icon: "🔭", isEmoji: true, rarity: "uncommon", sfx: "questComplete" },
  "flower-vase": { id: "flower-vase", name: "Flower Vase", category: "decor", icon: "🏺", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "picnic-blanket": { id: "picnic-blanket", name: "Picnic Blanket", category: "decor", icon: "🧺", isEmoji: true, rarity: "uncommon", sfx: "bagRustle" },
  "blueprint-marine-biology-lab": { id: "blueprint-marine-biology-lab", name: "Marine Biology Lab Blueprint", category: "special", icon: "🔬", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "blueprint-smoothie-bar": { id: "blueprint-smoothie-bar", name: "Smoothie Bar Blueprint", category: "special", icon: "🥤", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "blueprint-cadence-nursery": { id: "blueprint-cadence-nursery", name: "Baby Cadence's Nursery Blueprint", category: "special", icon: "🍼", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "magnifying-glass": { id: "magnifying-glass", name: "Brass Magnifying Glass", category: "special", icon: "🔎", isEmoji: true, rarity: "uncommon", sfx: "questComplete" },
  "paint-pigment": { id: "paint-pigment", name: "Paint Pigment", category: "decor", icon: "🎨", isEmoji: true, rarity: "common", sfx: "paintPigment" },
  "ink-midnight-blue": { id: "ink-midnight-blue", name: "Midnight Blue Ink", category: "decor", icon: "🔵", isEmoji: true, rarity: "uncommon", sfx: "paintPigment" },
  "ink-seaglass-teal": { id: "ink-seaglass-teal", name: "Sea-Glass Teal Ink", category: "decor", icon: "🟦", isEmoji: true, rarity: "uncommon", sfx: "paintPigment" },
  "ink-coral-pink": { id: "ink-coral-pink", name: "Coral Pink Ink", category: "decor", icon: "🩷", isEmoji: true, rarity: "uncommon", sfx: "paintPigment" },
  "ink-seaweed-green": { id: "ink-seaweed-green", name: "Seaweed Green Ink", category: "decor", icon: "🟢", isEmoji: true, rarity: "uncommon", sfx: "paintPigment" },
  "ink-pearl-shimmer": { id: "ink-pearl-shimmer", name: "Pearl-Shimmer Ink", category: "decor", icon: "⚪", isEmoji: true, rarity: "rare", sfx: "pearl", glows: true },
  "ink-pumpkin-orange": { id: "ink-pumpkin-orange", name: "Pumpkin Orange Ink", category: "decor", icon: "🟠", isEmoji: true, rarity: "rare", sfx: "paintPigment" },
  "glitter": { id: "glitter", name: "Sea Glitter", category: "decor", icon: "✨", isEmoji: true, rarity: "common", sfx: "craftSuccess" },
  "rescue-balloon": { id: "rescue-balloon", name: "Rescue Balloon", category: "trash", icon: "🎈", isEmoji: true, rarity: "common", sfx: "plastic" },
  "kelp-resin": { id: "kelp-resin", name: "Kelp Resin", category: "raw", icon: "🟩", isEmoji: true, rarity: "uncommon", sfx: "seaweedCollect" },
  "pure-water": { id: "pure-water", name: "Pure Water Vial", category: "special", icon: "💧", isEmoji: true, rarity: "uncommon", sfx: "liquidBottle" },
  "food-kelp-cookie": { id: "food-kelp-cookie", name: "Warm Kelp Cookie", category: "food", icon: "🍪", isEmoji: true, rarity: "uncommon", sfx: "craftSuccess" },
  "fresh-reef-fish": { id: "fresh-reef-fish", name: "Fresh Reef Fish", category: "food", icon: "🐟", isEmoji: true, rarity: "common", sfx: "oceanWaterSplash" },
  "shell-opal-rare": { id: "shell-opal-rare", name: "Rare Opal Shell", category: "shell", icon: "🐚", isEmoji: true, rarity: "rare", sfx: "shell" },
  "blueprint-wind-chime": { id: "blueprint-wind-chime", name: "Frosted Glass Wind Chime Blueprint", category: "special", icon: "📋", isEmoji: true, rarity: "uncommon", sfx: "questComplete" },
  "pattern-pastel-wave": { id: "pattern-pastel-wave", name: "Pastel Wave Shell Paint Pattern", category: "special", icon: "📋", isEmoji: true, rarity: "uncommon", sfx: "questComplete" },
  "display-mariners-compass": { id: "display-mariners-compass", name: "Restored Mariner's Compass Display Item", category: "special", icon: "🧭", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "museum-painted-vase": { id: "museum-painted-vase", name: "Restored Painted Harbor Vase", category: "special", icon: "🏺", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "museum-harbor-sign": { id: "museum-harbor-sign", name: "Restored Old Harbor Sign", category: "special", icon: "🪧", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "museum-captains-map": { id: "museum-captains-map", name: "Restored Captain's Island Map", category: "special", icon: "🗺️", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "salvage-brass-key": { id: "salvage-brass-key", name: "Captain's Brass Key", category: "special", icon: "🔑", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "salvage-porcelain-cup": { id: "salvage-porcelain-cup", name: "Blue Porcelain Teacup", category: "special", icon: "☕", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "salvage-spyglass": { id: "salvage-spyglass", name: "Captain's Spyglass", category: "special", icon: "🔭", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "salvage-ship-lantern": { id: "salvage-ship-lantern", name: "Cabin Oil Lantern", category: "special", icon: "🏮", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "salvage-dolphin-carving": { id: "salvage-dolphin-carving", name: "Carved Dolphin Figure", category: "special", icon: "🐬", isEmoji: true, rarity: "rare", sfx: "questComplete" },
  "salvage-silver-spoon": { id: "salvage-silver-spoon", name: "Engraved Silver Spoon", category: "special", icon: "🥄", isEmoji: true, rarity: "rare", sfx: "questComplete" },
};

export const BEACH_SPAWN_POOL: { id: string; weight: number }[] = [
  { id: "shell-scallop", weight: 12 },
  { id: "shell-whelk", weight: 10 },
  { id: "shell-cowrie", weight: 10 },
  { id: "shell-clam", weight: 8 },
  { id: "shell-conch", weight: 6 },
  { id: "shell-nautilus", weight: 5 },
  { id: "shell-sanddollar", weight: 5 },
  { id: "shell-murex", weight: 4 },
  { id: "shell-abalone", weight: 2 },
  { id: "glass-green", weight: 10 },
  { id: "glass-white", weight: 9 },
  { id: "glass-teal", weight: 8 },
  { id: "glass-amber", weight: 6 },
  { id: "glass-blue", weight: 6 },
  { id: "glass-pink", weight: 5 },
  { id: "glass-purple", weight: 3 },
  { id: "glass-red", weight: 3 },
  { id: "glass-rainbow", weight: 1 },
  { id: "raw-driftwood-arch", weight: 8 },
  { id: "raw-driftwood-planks", weight: 5 },
  { id: "raw-barnacle-wood", weight: 5 },
  { id: "raw-stone", weight: 8 },
  { id: "raw-pebbles", weight: 8 },
  { id: "coconut", weight: 6 },
  { id: "trash-plastic", weight: 10 },
  { id: "pearl-silver", weight: 1 },
  { id: "pearl-pink", weight: 1 },
  { id: "pearl-blue", weight: 1 },
  { id: "pearl-yellow", weight: 1 },
  { id: "pearl-purple", weight: 1 },
  { id: "pearl-red", weight: 1 },
  { id: "pearl-white", weight: 2 },
  { id: "wild-beach-plum", weight: 7 },
  { id: "sea-rose-petal", weight: 6 },
  { id: "seaweed-fronds", weight: 8 },
  { id: "soothing-sea-salt", weight: 8 },
  { id: "beach-ball", weight: 4 },
  { id: "hemp-thread", weight: 6 },
  { id: "washed-up-canvas", weight: 5 },
  { id: "dried-sea-oats", weight: 7 },
  { id: "shiny-soda-tab", weight: 6 },
  { id: "driftwood-oar", weight: 3 },
  { id: "sealed-frosted-bottle", weight: 5 },
  { id: "sand-apricot", weight: 5 },
  { id: "sand-snow-white", weight: 6 },
  { id: "firefly-jar", weight: 2 },
];

export const COVE_SPAWN_POOL: { id: string; weight: number }[] = [
  { id: "shell-sanddollar", weight: 12 },
  { id: "shell-abalone", weight: 8 },
  { id: "shell-nautilus", weight: 6 },
  { id: "glass-purple", weight: 10 },
  { id: "glass-red", weight: 8 },
  { id: "glass-rainbow", weight: 6 },
  { id: "glass-blue", weight: 8 },
  { id: "glass-pink", weight: 8 },
  { id: "pearl-silver", weight: 6 },
  { id: "pearl-pink", weight: 6 },
  { id: "pearl-black", weight: 5 },
  { id: "pearl-green", weight: 5 },
  { id: "pearl-amber", weight: 5 },
  { id: "pearl-blue", weight: 6 },
  { id: "pearl-yellow", weight: 5 },
  { id: "pearl-purple", weight: 5 },
  { id: "pearl-red", weight: 6 },
  { id: "pearl-white", weight: 5 },
  { id: "raw-driftwood-planks", weight: 4 },
  { id: "wild-beach-plum", weight: 4 },
  { id: "copper-wire", weight: 6 },
  { id: "sand-pink", weight: 6 },
  { id: "sand-black-obsidian", weight: 4 },
  { id: "salt-crystal-pink", weight: 5 },
];

export const REEF_SPAWN_POOL: { id: string; weight: number }[] = [
  { id: "raw-driftwood-arch", weight: 14 },
  { id: "raw-driftwood-planks", weight: 10 },
  { id: "raw-barnacle-wood", weight: 10 },
  { id: "pearl-green", weight: 6 },
  { id: "pearl-amber", weight: 6 },
  { id: "pearl-yellow", weight: 4 },
  { id: "pearl-purple", weight: 6 },
  { id: "pearl-red", weight: 6 },
  { id: "pearl-white", weight: 5 },
  { id: "glass-rainbow", weight: 4 },
  { id: "glass-purple", weight: 6 },
  { id: "shell-abalone", weight: 5 },
  { id: "copper-wire", weight: 6 },
  { id: "sand-teal", weight: 6 },
  { id: "sand-red-ruby", weight: 4 },
  { id: "coral-bulb", weight: 10 },
  { id: "fertilizer", weight: 10 },
  { id: "kelp", weight: 12 },
];

export const SANDBAR_SPAWN_POOL: { id: string; weight: number }[] = [
  { id: "shell-sanddollar", weight: 8 },
  { id: "glass-rainbow", weight: 5 },
  { id: "pearl-amber", weight: 5 },
  { id: "pearl-yellow", weight: 5 },
  { id: "pearl-purple", weight: 4 },
  { id: "pearl-red", weight: 4 },
  { id: "pearl-white", weight: 5 },
  { id: "shiny-soda-tab", weight: 8 },
  { id: "sand-apricot", weight: 8 },
  { id: "sand-teal", weight: 6 },
  { id: "sand-snow-white", weight: 10 },
  { id: "star-sand", weight: 3 },
  { id: "fresh-reef-fish", weight: 5 },
];

function rollFrom(pool: { id: string; weight: number }[]): string {
  const total = pool.reduce((s, e) => s + e.weight, 0);
  let r = Math.random() * total;
  for (const entry of pool) {
    if (r < entry.weight) return entry.id;
    r -= entry.weight;
  }
  return pool[0].id;
}

export function rollSpawn(): string {
  return rollFrom(withOrangePearl(BEACH_SPAWN_POOL, 1));
}

export function rollCoveSpawn(): string {
  return rollFrom(withOrangePearl(COVE_SPAWN_POOL, 5));
}

export function rollReefSpawn(iridescentFlakesUnlocked = false): string {
  const pool = withOrangePearl(REEF_SPAWN_POOL, 5);
  return rollFrom(iridescentFlakesUnlocked ? [...pool, { id: "shell-flake-blue", weight: 4 }] : pool);
}

export function rollSandbarSpawn(): string {
  return rollFrom(withOrangePearl(SANDBAR_SPAWN_POOL, 5));
}

/** Orange Pearls permanently enter circulation on October 1, 2026. */
export function isOrangePearlUnlocked(now = new Date()): boolean {
  return now.getFullYear() > 2026 || (now.getFullYear() === 2026 && now.getMonth() >= 9);
}

function withOrangePearl(pool: { id: string; weight: number }[], weight: number) {
  return isOrangePearlUnlocked() ? [...pool, { id: "pearl-orange", weight }] : pool;
}
