export interface QuestDef {
  id: string;
  title: string;
  from: string;
  letter: string;
  requires: { itemId: string; count: number }[];
  requiresCraft?: string;
  requiresFlag?: string;
  rewardItemId?: string;
  rewardCount?: number;
  rewardLabel: string;
  unlocksWorkshop?: boolean;
  phase: 1 | 2 | 3 | 4;
}

export const QUESTS: QuestDef[] = [
  {
    id: "botanist",
    title: "The Wandering Botanist",
    from: "A traveling botanist",
    letter: "Dear Beachkeeper, I am studying the flora of the outer islands, but my supply of soil-enriching materials has run low. I hear the coconuts on your beach are exceptionally nutrient-rich! If you could shake a few down and gather them, I would be eternally grateful.",
    requires: [{ itemId: "coconut", count: 3 }],
    rewardLabel: "Wild Hibiscus Seeds 🌺",
    phase: 1,
  },
  {
    id: "shellseeker",
    title: "A Cozy Shell-Seeker",
    from: "Barnaby the hermit crab",
    letter: "Hello Friend, I am a little hermit crab named Barnaby writing from a windy sandbar nearby. My current shell is getting dreadfully tight! If you find a smooth, spiraled whelk shell on your shore, could you set it aside for me?",
    requires: [{ itemId: "shell-whelk", count: 1 }],
    rewardItemId: "pearl-pink",
    rewardCount: 1,
    rewardLabel: "A sparkling Pink Pearl",
    phase: 1,
  },
  {
    id: "harbormaster",
    title: "The Harbor Master",
    from: "The Harbor Master",
    letter: "To the Shoreline Sanctuary, our shipping lanes are getting cluttered with floating debris. If you could help me recycle some of the plastic clutter clogging up your shoreline, it would help the whole bay breathe a little easier.",
    requires: [{ itemId: "trash-plastic", count: 5 }],
    rewardItemId: "raw-driftwood-planks",
    rewardCount: 1,
    rewardLabel: "A Weathered Boat Plank (keep this rare salvage for later)",
    phase: 1,
  },
  {
    id: "glassartisan",
    title: "The Glass Artisan",
    from: "A city mosaic designer",
    letter: "Greetings, Fellow Creator! I design mosaics in the city, but nothing compares to the smooth, frosty beauty of ocean-tumbled sea glass. I am looking for a few pieces of pale-green sea glass to finish my latest window. Could you search the tide line for me?",
    requires: [{ itemId: "glass-green", count: 4 }],
    rewardLabel: "Blueprints for crafting Melodic Wind Chimes",
    unlocksWorkshop: true,
    phase: 1,
  },
  {
    id: "marinebiologist",
    title: "The Marine Biologist",
    from: "A marine biologist studying the reef",
    letter: "Dear Sanctuary Caretaker, I am tracking a highly elusive species of fish called the Rainbow Seahorse. They love to hide near colorful, handmade structures. If you could build a small grotto out of your colorful sea glass, we might just spot one!",
    requires: [],
    requiresCraft: "fish-grotto",
    requiresFlag: "rowboatRepaired",
    rewardItemId: "trophy-nautilus",
    rewardCount: 1,
    rewardLabel: "A highly prized Golden Nautilus Shell",
    phase: 2,
  },
  {
    id: "stargazer",
    title: "The Star-Gazer",
    from: "A distant observatory watcher",
    letter: "To the One Looking Up, I watch the stars from a distant observatory. Sometimes, rare celestial dust falls into the ocean and washes ashore as glowing, neon-colored glass. If you find any of this 'glowing glass', please keep it safe — it holds the light of the stars.",
    requires: [{ itemId: "glass-rainbow", count: 3 }],
    requiresFlag: "rowboatRepaired",
    rewardItemId: "trophy-brass-dial",
    rewardCount: 1,
    rewardLabel: "A Weathered Brass Dial (a vintage shipwreck restoration part)",
    phase: 2,
  },
  {
    id: "reefguardian",
    title: "The Reef Guardian",
    from: "A migrating pod of whales",
    letter: "Urgent Message from the Deep, A migrating pod of whales just passed by, but they report that a giant, forgotten nylon fishing net has snagged on the coral reef below your shore. It's trapping the local fish. Please, put on your diving gear and help us clear it!",
    requires: [],
    requiresFlag: "ghostNetCut",
    rewardItemId: "trophy-ship-bell",
    rewardCount: 1,
    rewardLabel: "A beautifully oxidised, historic Old Ship Bell",
    phase: 3,
  },
  {
    id: "shipsghost",
    title: "The Ship's Ghost",
    from: "The captain of the Sovereign",
    letter: "To the Living Soul Above, Centuries ago, I was the captain of the Sovereign. We hit a reef during a great storm, and my beautiful ship was lost to the tides. I do not wish for gold — only to see my old ship home to the ocean's creatures once more. Will you help rebuild her bones?",
    requires: [],
    requiresFlag: "shipRestored",
    rewardItemId: "trophy-rose-window",
    rewardCount: 1,
    rewardLabel: "Exclusive Mosaic Rose Window blueprints for the captain's cabin",
    phase: 3,
  },
  {
    id: "grandreunion",
    title: "The Grand Reunion",
    from: "Every friend of the sanctuary",
    letter: "Dear Friend of the Ocean, Word of your sanctuary has reached ports far and wide! A group of us — botanists, artisans, and sailors alike — are boarding a boat to visit your legendary shores. We cannot wait to see the restored ship and the thriving marine life you have nurtured.",
    requires: [],
    requiresFlag: "shipRestored",
    rewardLabel: "The Grand Finale! Your sanctuary becomes a living Marine Museum.",
    phase: 3,
  },
  {
    id: "oliverpicnic",
    title: "The Picnic Basket Panic",
    from: "Oliver, the Distapped Traveler",
    letter: "Hello friend! If you are reading this, I hope your blanket is firmly anchored. I set up a beautiful spot near the dunes yesterday afternoon, opened my woven wicker basket, and poured a cold glass of Coconut Milk. The view was magnificent! But then... it happened. A shadow fell, a thunderous flap of wings echoed, and a chubby seagull dive-bombed right into my snacks! In the panic, I dropped my favorite journal somewhere in the sand. Could you help me find it? I hear those birds love trading shiny things if you leave a treat out for them.",
    requires: [],
    requiresFlag: "seagullTraded",
    rewardItemId: "glass-teal",
    rewardCount: 5,
    rewardLabel: "Rare Blueprint: Vintage Beach Blanket & 5x Polished Teal Sea Glass",
    phase: 4,
  },
  {
    id: "marinaumbrella",
    title: "Snappy's Sunscreen Alternative",
    from: "Marina, the Marine Biologist",
    letter: "Greetings from across the bay! I've been monitoring the local shorelines, and I noticed that Snappy the Sea Turtle has been spending a lot of time resting up on the hot sand dunes lately. While he loves the afternoon heat, the mid-day sun can get a bit too intense for his shell! We need a zero-stress way to keep him cool while he naps. I've sent over a design to piece together a shade shelter. If you can gather enough driftwood and washed-up canvas from the shore, we can set up a personal canopy right over his favorite resting spot!",
    requires: [],
    requiresCraft: "beach-umbrella",
    rewardItemId: "pearl-silver",
    rewardCount: 1,
    rewardLabel: "Snappy's Blessing (increases local crab happiness) & 1x Sparkling Silver Pearl",
    phase: 4,
  },
  {
    id: "vancebeachbag",
    title: "The Lost Luggage Mystery",
    from: "Captain Vance, of the Stray Rowboat",
    letter: "To whoever finds this message! My cargo ship caught a rogue wave just off the Hidden Cove last week. While the ship survived, a heavy gust of wind caught our supply deck and sent several of our newly tailored inventory expansion bags tumbling right into the surf. They are incredibly tough, made of heavy canvas duck cloth and twisted hemp rope, so they won't get ruined by the salt—but the tide has likely buried them deep under the coastal dunes by now. Keep an eye out for a mint-green strap peeking through the sand oats!",
    requires: [],
    requiresFlag: "hasBeachBag",
    rewardItemId: "shiny-soda-tab",
    rewardCount: 12,
    rewardLabel: "Permanent Mobile Inventory Expansion (+10 Slots) & 12x Shiny Soda Tabs",
    phase: 4,
  },
];
